### PR TITLE
flaskutils-admin

### PR DESCRIPTION
**Pull request by niallryan**
Command line tool for generating new flaskutils projects

@maigfrga @Rondineli @cormacp 

https://trello.com/c/oTmMYLn2/2089-3-add-create-project-command-to-flaskutils

### CODE REVIEW

**Comment by cormacp** [comment]
👍

**Comment by mfranco** [comment]
It should be only about  create the source code structure, not vagrant or docker stuff, other that it seems ok

**Comment by mfranco** [comment]
Almost  there, We don't need bdd stuff as people not necessary use it.

**Comment by niallryan** [comment]
@maigfrga Done 👍

**Comment by mfranco** [comment]
:+1:

**Pull request merged**
